"""Generate every results table of the preprint from hesp_research/results/*_summary.json.

Numbers in the paper's tables are never typed by hand. Run after any summary changes:

    python paper/make_tables.py        # writes paper/tables/*.tex
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
RESULTS = HERE.parent / "hesp_research" / "results"
OUT = HERE / "tables"
QWEN = [("7b", "Qwen2.5-7B"), ("32b", "Qwen2.5-32B"), ("72b", "Qwen2.5-72B")]
V08_MODELS = [("qwen7b", "Q-7B"), ("qwen32b", "Q-32B"), ("qwen72b", "Q-72B"), ("llama8b", "L-8B"), ("llama70b", "L-70B")]


def ci(d, lo_hi_key="ci"):
    lo, hi = d[lo_hi_key]
    return f"{d['difference']:+.3f} [{lo:+.2f}, {hi:+.2f}]"


def write(name, lines):
    OUT.mkdir(exist_ok=True)
    (OUT / f"{name}.tex").write_text("% generated by paper/make_tables.py -- do not edit\n" + "\n".join(lines) + "\n",
                                     encoding="utf-8")


def v06():
    s = json.loads((RESULTS / "v06_summary.json").read_text(encoding="utf-8"))
    arms = [("react_style", "ReAct-style"), ("memory_only", "Memory-only"),
            ("hesp_eigc_guard_emp20", "HESP, empirical table ($k{=}20$)"),
            ("hesp_eigc_guard_designer", "HESP, designer table"),
            ("hesp_eigc_guard_llmp", "HESP, LLM-elicited table")]
    L = [r"\begin{tabular}{lrrr}", r"\toprule", "Arm & " + " & ".join(m for _, m in QWEN) + r" \\", r"\midrule"]
    for a, label in arms:
        L.append(f"{label} & " + " & ".join(f"{s[k]['verified'][a]:.3f}" for k, _ in QWEN) + r" \\")
    L.append(r"\midrule")
    key = "hesp_eigc_guard_emp20_minus_memory_only"
    L.append(r"$\Delta$ empirical $-$ Memory-only & " + " & ".join(
        ci(s[k]["paired_verification"][key], "cluster_bootstrap_percentile_95") for k, _ in QWEN) + r" \\")
    key = "hesp_eigc_guard_designer_minus_hesp_eigc_guard_emp20"
    L.append(r"$\Delta$ designer $-$ empirical & " + " & ".join(
        ci(s[k]["paired_verification"][key], "cluster_bootstrap_percentile_95") for k, _ in QWEN) + r" \\")
    L.append(r"Mean probe cost, Memory-only / empirical & " + " & ".join(
        f"{s[k]['mean_tool_cost']['memory_only']:.2f} / {s[k]['mean_tool_cost']['hesp_eigc_guard_emp20']:.2f}"
        for k, _ in QWEN) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("v06_main", L)

    L = [r"\begin{tabular}{llrrrrr}", r"\toprule",
         r"Model & Arm & claimed & unresolved & missed attack & false escalation & wrong cause \\", r"\midrule"]
    fmt = lambda x: "n/a" if x is None else f"{x:.2f}"
    for k, m in QWEN:
        for a, label in (("react_style", "ReAct-style"), ("memory_only", "Memory-only"),
                         ("hesp_eigc_guard_emp20", "HESP (empirical)")):
            sm = s[k]["security_metrics_corrected"][a]
            L.append(f"{m} & {label} & {sm['episodes_with_a_claim']}/{sm['episodes']} & {fmt(sm['unresolved_rate'])} & "
                     f"{fmt(sm['missed_attack_rate'])} & {fmt(sm['false_escalation_rate'])} & {fmt(sm['wrong_cause_rate'])}" + r" \\")
        L.append(r"\midrule" if k != "72b" else r"\bottomrule")
    L.append(r"\end{tabular}")
    write("v06_security", L)


def v08():
    s = json.loads((RESULTS / "v08_summary.json").read_text(encoding="utf-8"))
    arms = [("memory_only", "Memory-only (LLM picks)"), ("hesp_random_blind", "controller, random"),
            ("hesp_eigc_blind", "controller, EIG/cost"), ("hesp_eigc", "\\quad + ranking shown"),
            ("hesp_eigc_guard", "\\quad + finish guard")]
    L = [r"\begin{tabular}{l" + "r" * len(V08_MODELS) + "}", r"\toprule",
         "Arm & " + " & ".join(m for _, m in V08_MODELS) + r" \\", r"\midrule"]
    for a, label in arms:
        L.append(f"{label} & " + " & ".join(f"{s[k]['verified'][a]:.3f}" for k, _ in V08_MODELS) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("v08_verified", L)

    terms = [("hesp_random_blind - memory_only", "hand probe choice to controller"),
             ("hesp_eigc_blind - hesp_random_blind", "EIG/cost ranking itself"),
             ("hesp_eigc_guard - memory_only", "full HESP vs Memory-only")]
    L = [r"\begin{tabular}{l" + "c" * len(V08_MODELS) + "}", r"\toprule",
         "Term & " + " & ".join(m for _, m in V08_MODELS) + r" \\", r"\midrule"]
    for t, label in terms:
        cells = []
        for k, _ in V08_MODELS:
            d = s[k]["terms"][t]
            cells.append(r"\makecell{" + f"{d['difference']:+.3f}" + r"\\ \scriptsize" +
                         f"[{d['ci'][0]:+.2f}, {d['ci'][1]:+.2f}]" + "}")
        L.append(f"{label} & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("v08_terms", L)


def v09():
    path = RESULTS / "v09_summary.json"
    if not path.exists():
        write("v09_main", [r"\fbox{\parbox{0.9\linewidth}{\centering v0.9 results pending (pre-registered; see Appendix~\ref{app:prereg}).}}"])
        return
    s = json.loads(path.read_text(encoding="utf-8"))
    arms = [("memory_only", "LLM", "LLM"), ("memory_only_autostop", "LLM", "LLM or controller"),
            ("hesp_eigc_blind", "controller (EIG/cost)", "LLM"),
            ("hesp_eigc_blind_autostop", "controller (EIG/cost)", "LLM or controller"),
            ("hesp_random_blind_autostop", "controller (random)", "LLM or controller")]
    models = [(k, m) for k, m in V08_MODELS if k in s]
    L = [r"\begin{tabular}{ll" + "r" * len(models) + "}", r"\toprule",
         "Who probes & Who stops & " + " & ".join(m for _, m in models) + r" \\", r"\midrule"]
    for a, probes, stops in arms:
        L.append(f"{probes} & {stops} & " + " & ".join(
            f"{s[k]['verified'][a]:.3f} {{\\scriptsize({s[k]['tool_cost'][a]:.1f})}}" for k, _ in models) + r" \\")
    ref_path = RESULTS / "v09_llm_free_reference.json"
    if ref_path.exists():
        ref = json.loads(ref_path.read_text(encoding="utf-8"))
        L.append(r"\midrule")
        L.append(r"\multicolumn{" + str(2 + len(models)) + r"}{l}{\textit{No LLM (post hoc reference, same seeds, tasks and budget)}} \\")
        for a, probes in (("fixed_order_autostop", "catalogue order"), ("controller_eigc_autostop", "controller (EIG/cost)"),
                          ("controller_random_autostop", "controller (random)")):
            L.append(f"{probes} & controller & " + r"\multicolumn{" + str(len(models)) + r"}{c}{" +
                     f"{ref['verified'][a]:.3f} {{\\scriptsize({ref['tool_cost'][a]:.1f})}}" + r"} \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("v09_main", L)

    terms = [("hesp_eigc_blind_autostop - hesp_eigc_blind", "controller stop, controller probes (P1 on L-8B)"),
             ("hesp_eigc_blind_autostop - memory_only_autostop", "who probes, stop supplied (P2 on L-8B)"),
             ("memory_only_autostop - memory_only", "controller stop, LLM probes"),
             ("hesp_eigc_blind_autostop - hesp_random_blind_autostop", "EIG/cost ranking under controller stop")]
    L = [r"\begin{tabular}{l" + "c" * len(models) + "}", r"\toprule",
         "Term & " + " & ".join(m for _, m in models) + r" \\", r"\midrule"]
    for t, label in terms:
        cells = []
        for k, _ in models:
            d = s[k]["terms"][t]
            cells.append(r"\makecell{" + f"{d['difference']:+.3f}" + r"\\ \scriptsize" +
                         f"[{d['ci'][0]:+.2f}, {d['ci'][1]:+.2f}]" + "}")
        L.append(f"{label} & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("v09_terms", L)


V10_MODELS = [("qwen7b", "Q-7B"), ("llama8b", "L-8B"), ("qwen32b", "Q-32B"), ("qwen72b", "Q-72B"), ("llama70b", "L-70B")]


def v10a():
    """Part A: verified completion on the external sigma-triage family, and the two primary contrasts."""
    s = json.loads((RESULTS / "v10a_summary.json").read_text(encoding="utf-8"))
    arms = [("memory_only", "LLM", "LLM"), ("memory_only_autostop", "LLM", "LLM or controller"),
            ("hesp_eigc_blind", "controller (EIG/cost)", "LLM"),
            ("hesp_eigc_blind_autostop", "controller (EIG/cost)", "LLM or controller"),
            ("hesp_random_blind_autostop", "controller (random)", "LLM or controller")]
    models = [(k, m) for k, m in V10_MODELS if k in s]
    L = [r"\begin{tabular}{ll" + "r" * len(models) + "}", r"\toprule",
         "Who probes & Who stops & " + " & ".join(m for _, m in models) + r" \\", r"\midrule"]
    for a, probes, stops in arms:
        L.append(f"{probes} & {stops} & " + " & ".join(
            f"{s[k]['verified'][a]:.3f} {{\scriptsize({s[k]['tool_cost'][a]:.1f})}}" for k, _ in models) + r" \\")
    L.append(r"\midrule")
    for t, label in (("hesp_eigc_blind_autostop - hesp_random_blind_autostop", r"$\Delta$ ranking (PA1 on Q-7B)"),
                     ("hesp_eigc_blind_autostop - memory_only", r"$\Delta$ full (PA2 on Q-7B)")):
        cells = []
        for k, _ in models:
            d = s[k]["terms"][t]
            cells.append(r"\makecell{" + f"{d['difference']:+.3f}" + r"\ \scriptsize" +
                         f"[{d['ci'][0]:+.2f}, {d['ci'][1]:+.2f}]" + "}")
        L.append(r"\multicolumn{2}{l}{" + label + "} & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("v10a_main", L)


def v10b():
    """Part B: controller behaviour under table mismatch (LLM-free), for each family present."""
    fams = [(f, lab) for f, lab in (("sec", "sec-triage"), ("sigma", "sigma-triage"))
            if (RESULTS / f"v10b_{f}" / "summary.json").exists()]
    data = {f: json.loads((RESULTS / f"v10b_{f}" / "summary.json").read_text(encoding="utf-8"))["results"] for f, _ in fams}
    conds = [("M0_matched", "matched tables"), ("M1_base_only", "base variant only"),
             ("M4_k1_base_only", r"$k{=}1$, base only"), ("M2_lambda0.25", r"perturbed, $\lambda{=}0.25$"),
             ("M2_lambda0.5", r"perturbed, $\lambda{=}0.5$"), ("M2_lambda0.75", r"perturbed, $\lambda{=}0.75$"),
             ("M3_missing[mean]", "one cause missing (mean)")]
    cols = "l" + "rrrrr" * len(fams)
    L = [r"\begin{tabular}{" + cols + "}", r"\toprule",
         " & " + " & ".join(r"\multicolumn{5}{c}{" + lab + "}" for _, lab in fams) + r" \\",
         " ".join(r"\cmidrule(lr){" + f"{2 + 5 * i}-{6 + 5 * i}" + "}" for i in range(len(fams))),
         "Tables & " + " & ".join(["verif. & correct, unverif. & wrong & esc. & random verif."] * len(fams)) + r" \\",
         r"\midrule"]
    for c, label in conds:
        cells = []
        for f, _ in fams:
            e, r = data[f][c]["eig_cost"], data[f][c]["random"]
            # the four classes are exhaustive: what is neither verified, wrong, nor escalated is the right cause
            # without a confirming signature
            unver = max(0.0, 1 - e["verified"] - e["wrong"] - e["escalated"])
            cells += [f"{e['verified']:.3f}", f"{unver:.3f}", f"{e['wrong']:.3f}", f"{e['escalated']:.3f}",
                      f"{r['verified']:.3f}"]
        L.append(f"{label} & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("v10b_main", L)


def v10c():
    """Part C: attack success under injected instructions and spoofed evidence, per model and arm."""
    s = json.loads((RESULTS / "v10c_summary.json").read_text(encoding="utf-8"))
    arms = [("react_style", "ReAct"), ("memory_only", "Mem."), ("hesp_guard_autostop", r"\hesp{}"),
            ("hesp_guard_autostop_corroborate", r"\hesp{}+corr.")]
    models = [(k, m) for k, m in V10_MODELS if k in s]
    L = [r"\begin{tabular}{l" + "rrrr" * 2 + "rr}", r"\toprule",
         r" & \multicolumn{4}{c}{Injected instruction: attack success} & \multicolumn{4}{c}{Spoofed evidence: attack success}"
         r" & \multicolumn{2}{c}{Benign cases: verified} \\",
         r"\cmidrule(lr){2-5}\cmidrule(lr){6-9}\cmidrule(lr){10-11}",
         "Model & " + " & ".join(a for _, a in arms) + " & " + " & ".join(a for _, a in arms) +
         r" & \hesp{} & \hesp{}+corr. \\", r"\midrule"]
    for k, m in models:
        t = s[k]["table"]
        def count(v, a, metric):
            c = t[v][a]
            return f"{round(c[metric] * c['episodes'])}/{c['episodes']}"
        cells = [count("inject", a, "attack_success") for a, _ in arms]
        cells += [count("spoof", a, "attack_success") for a, _ in arms]
        cells += [count("base", a, "verified") for a in ("hesp_guard_autostop", "hesp_guard_autostop_corroborate")]
        L.append(f"{m} & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("v10c_main", L)


if __name__ == "__main__":
    v06()
    v08()
    v09()
    v10a()
    v10b()
    v10c()
    print("tables written to", OUT)
