"""Generate the tables and the figure of the benchmark-shortcut paper from hesp_research/results/audit/*.

Numbers in the paper are never typed by hand. Run after any audit output changes:

    python paper/make_audit.py        # writes paper/tables/audit_*.tex and paper/figures/fig_shortcut.pdf
"""
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
RES = HERE.parent / "hesp_research" / "results"
AUD = RES / "audit"
OUT = HERE / "tables"


def load(name):
    return json.loads((AUD / name).read_text(encoding="utf-8"))


def write(name, lines):
    OUT.mkdir(exist_ok=True)
    (OUT / f"{name}.tex").write_text("% generated by paper/make_audit.py -- do not edit\n" + "\n".join(lines) + "\n",
                                     encoding="utf-8")


def pct(x):
    return f"{100 * x:.1f}"


def macros(m):
    """Numbers quoted in the prose, as LaTeX macros (\\newcommand), so the text never retypes them."""
    L = [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in m.items()]
    write("audit_numbers", L)


def guide_numbers():
    t = (AUD / "guide_diagnose.txt").read_text(encoding="utf-8")
    hist = re.search(r"org\+detector history\s+accuracy ([\d.]+)\s+TP recall ([\d.]+)", t)
    maj = re.search(r"global majority\s+accuracy ([\d.]+)", t)
    mi = re.search(r"I\(grade; org\) = ([\d.]+) bits\s+H\(grade\) = ([\d.]+)", t)
    seen = re.search(r"seen in the org's past: ([\d.]+)%", t)
    split = re.search(r"fit ([\d,]+), dev ([\d,]+)", t)
    inc = re.search(r"([\d,]+) incidents in ([\d,]+) orgs", t)
    det = re.search(r"detector\s+([\d.]+)\s*$", t, re.M)
    ent = re.search(r"entity_types\s+([\d.]+) -> ([\d.]+)", t)
    held = (AUD / "guide_orgheldout.txt").read_text(encoding="utf-8") if (AUD / "guide_orgheldout.txt").exists() else ""
    hmaj = re.search(r"majority-class accuracy on dev sample:\s*([\d.]+)", held)
    pil = json.loads((AUD / "guide_orgheldout.json").read_text(encoding="utf-8"))
    accs = [v["accuracy"] for k, v in pil.items() if isinstance(v, dict) and "accuracy" in v]
    return {"hist_acc": float(hist.group(1)), "hist_tp": float(hist.group(2)), "majority": float(maj.group(1)),
            "mi_org": float(mi.group(1)), "h_grade": float(mi.group(2)), "seen": float(seen.group(1)),
            "dev": split.group(2), "incidents": inc.group(1), "orgs": inc.group(2), "mi_det": float(det.group(1)),
            "ent_mi": float(ent.group(1)), "ent_mi_det": float(ent.group(2)),
            "held_majority": float(hmaj.group(1)) if hmaj else None, "held_min": min(accs), "held_max": max(accs)}


def main():
    tr, te = load("excytin_train_analysis.json"), load("excytin_test_analysis.json")
    rep = load("excytin_reported_table2.json")
    sia = load("siabench.json")["summary"]
    otrf = load("otrf.json")
    g = guide_numbers()
    v11 = json.loads((RES / "v11_summary.json").read_text(encoding="utf-8"))["D1"]
    comp = json.loads((RES / "v12b" / "summary.json").read_text(encoding="utf-8"))["results"]

    # ---- Table: ExCyTIn shortcut rates, train and test ----------------------------------------------------------
    rows = [("named", "Question names the end alert (rank 1 by word overlap)"),
            ("adjacent", "Answer is a neighbour of the end alert (upper bound)"),
            ("graph_correct", "Graph baseline answers exactly"),
            ("table_correct", "Alert-table baseline answers exactly")]
    L = [r"\begin{tabular}{lrr}", r"\toprule",
         f"Measure & Train ($n{{=}}{tr['questions']}$) & Test ($n{{=}}{te['questions']}$), 95\\% CI \\\\", r"\midrule"]
    for k, lab in rows:
        a, b = tr["rates"][k], te["rates"][k]
        lo, hi = b["ci95_incident_cluster"]
        L.append(f"{lab} & {pct(a['rate'])} & {pct(b['rate'])} [{pct(lo)}, {pct(hi)}] \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("audit_excytin", L)

    # ---- Table: per incident (appendix) ------------------------------------------------------------------------
    per = load("excytin_test.json")["summary"]["per_incident"]
    show = ["GPT-4o", "o3", "Claude-Opus-4.5"]
    L = [r"\begin{tabular}{lrrrr" + "r" * len(show) + "}", r"\toprule",
         "Incident & $n$ & Named & Graph & Table & " + " & ".join(show) + r" \\", r"\midrule"]
    for j, inc in enumerate(rep["incidents"]):
        p = per[inc]
        L.append(f"{inc.split('_')[1]} & {p['n']} & {pct(p['named'] / p['n'])} & {pct(p['graph_correct'] / p['n'])} & "
                 f"{pct(p['table_correct'] / p['n'])} & " + " & ".join(f"{100 * rep['models'][m][j]:.1f}" for m in show) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("audit_excytin_incidents", L)

    # ---- Table: per-model Spearman (appendix) ------------------------------------------------------------------
    h3 = te["h3"]
    items = sorted(h3["spearman_by_model"].items(), key=lambda kv: -te["reported_average_reward"][kv[0]])
    half = (len(items) + 1) // 2
    L = [r"\begin{tabular}{lrr@{\hspace{1.5em}}lrr}", r"\toprule",
         r"Model & Reward & $\rho$ & Model & Reward & $\rho$ \\", r"\midrule"]
    for i in range(half):
        a = items[i]
        cell = f"{a[0]} & {100 * te['reported_average_reward'][a[0]]:.1f} & {a[1]:+.2f}"
        if i + half < len(items):
            b = items[i + half]
            cell += f" & {b[0]} & {100 * te['reported_average_reward'][b[0]]:.1f} & {b[1]:+.2f}"
        else:
            cell += " & & &"
        L.append(cell + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("audit_h3", L)

    # ---- Table: all benchmarks --------------------------------------------------------------------------------
    rew = te["reported_average_reward"]
    graph = te["rates"]["graph_correct"]["rate"]
    table = te["rates"]["table_correct"]["rate"]
    below_graph = sum(v < graph for v in rew.values())
    below_table = sum(v < table for v in rew.values())
    best = max(rew.items(), key=lambda kv: kv[1])
    sia_rep = sia["reported_accuracy"]
    rule_acc = otrf["rule_accuracy"]
    L = [r"\begin{tabular}{p{1.45cm}p{2.0cm}p{2.15cm}p{1.6cm}}", r"\toprule",
         r"Benchmark & Shortcut & Investigation-free rule & Rule score \\", r"\midrule",
         f"ExCyTIn & S1: question names the answer's alert & read the named alert's entity & "
         f"{pct(graph)} (graph), {pct(table)} (table) \\\\",
         f"SIABench & S3: attacker address from data generation & TP iff alert involves 172.16.0.1 & "
         f"{sia['attacker_rule_correct']}/{sia['alerts']} \\\\",
         f"GUIDE & S2: label set by organisation policy & repeat the org's past grade for the detector & "
         f"{pct(g['hist_acc'])} \\\\",
         f"OTRF & S3: tool default names; benign = OS routine & flag non-system task or service names & "
         f"{otrf['distinct_alerts'] - otrf['attack_disguised_as_benign']}/{otrf['distinct_alerts']} \\\\",
         f"Built triage environments & S4: deterministic evidence model & LLM-free controller & "
         f"{v11['sec|eig_confirm']['verified']}/{v11['sec|eig_confirm']['episodes']}, "
         f"{v11['sigma|eig_confirm']['verified']}/{v11['sigma|eig_confirm']['episodes']} \\\\",
         r"\bottomrule", r"\end{tabular}"]
    write("audit_benchmarks", L)

    # ---- Numbers quoted in prose ------------------------------------------------------------------------------
    t = te["rates"]
    m = {
        "exTestN": te["questions"], "exTrainN": tr["questions"],
        "exNamed": pct(t["named"]["rate"]), "exNamedLo": pct(t["named"]["ci95_incident_cluster"][0]),
        "exNamedHi": pct(t["named"]["ci95_incident_cluster"][1]), "exNamedCount": t["named"]["count"],
        "exAdj": pct(t["adjacent"]["rate"]), "exGraph": pct(graph), "exGraphCount": t["graph_correct"]["count"],
        "exGraphLo": pct(t["graph_correct"]["ci95_incident_cluster"][0]),
        "exGraphHi": pct(t["graph_correct"]["ci95_incident_cluster"][1]),
        "exTable": pct(table), "exTableLo": pct(t["table_correct"]["ci95_incident_cluster"][0]),
        "exTableHi": pct(t["table_correct"]["ci95_incident_cluster"][1]),
        "exTrainNamed": pct(tr["rates"]["named"]["rate"]), "exTrainGraph": pct(tr["rates"]["graph_correct"]["rate"]),
        "exTrainTable": pct(tr["rates"]["table_correct"]["rate"]),
        "exModels": len(rew), "exBelowGraph": below_graph, "exBelowTable": below_table,
        "exBest": f"{100 * best[1]:.1f}", "exBestModel": best[0],
        "exGptFo": f"{100 * rew['GPT-4o']:.1f}", "exOThree": f"{100 * rew['o3']:.1f}",
        "exGptFourOne": f"{100 * rew['GPT-4.1']:.1f}",
        "hPos": h3["positive"], "hMedian": f"{h3['median']:.2f}", "hP": f"{h3['sign_test_one_sided_p']:.4f}",
        "siaN": sia["alerts"], "siaTP": sia["true_positive"], "siaRule": sia["attacker_rule_correct"],
        "siaMajority": sia["majority_correct"], "siaGptFive": pct(sia_rep["GPT-5"]),
        "siaSonnet": f"{100 * sia_rep['Claude-4.5-Sonnet']:.1f}", "siaMini": pct(sia_rep["GPT-4o-mini"]),
        "gHist": f"{g['hist_acc']:.3f}", "gHistTP": f"{g['hist_tp']:.3f}", "gMajority": f"{g['majority']:.3f}",
        "gMIorg": f"{g['mi_org']:.2f}", "gH": f"{g['h_grade']:.2f}", "gSeen": f"{g['seen']:.1f}",
        "gDev": g["dev"].replace(",", "{,}"), "gIncidents": g["incidents"].replace(",", "{,}"),
        "gOrgs": g["orgs"].replace(",", "{,}"), "gMIdet": f"{g['mi_det']:.2f}",
        "gEnt": f"{g['ent_mi']:.2f}", "gEntDet": f"{g['ent_mi_det']:.3f}",
        "gHeldMin": f"{g['held_min']:.2f}", "gHeldMax": f"{g['held_max']:.2f}",
        "gHeldMajority": f"{g['held_majority']:.3f}" if g["held_majority"] is not None else r"\todo{majority}",
        "otN": otrf["distinct_alerts"], "otAttack": otrf["attack_alerts"], "otBenign": otrf["benign_alerts"],
        "otRule": f"{rule_acc:.3f}", "otRec": otrf["recordings"], "otNamedAttack": otrf["attack_named_by_alert_text"],
        "envSec": v11["sec|eig_confirm"]["verified"], "envSecN": v11["sec|eig_confirm"]["episodes"],
        "envSigma": v11["sigma|eig_confirm"]["verified"], "envSigmaN": v11["sigma|eig_confirm"]["episodes"],
        "compSingle": comp["G1|comp|confirm@10"]["correct"], "compJoint": comp["G1|comp|joint@10"]["correct"],
        "compN": comp["G1|comp|confirm@10"]["episodes"], "compSingleEsc": comp["G1|comp|confirm@10"]["escalated"],
        "compJointMissed": comp["G1|comp|joint@10"]["missed_attack"],
    }
    macros(m)

    # ---- Figure: reported model rewards vs investigation-free baselines ---------------------------------------
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams.update({"font.family": "serif", "font.serif": ["Times New Roman", "DejaVu Serif"], "font.size": 8,
                         "axes.spines.top": False, "axes.spines.right": False, "pdf.fonttype": 42})
    names = sorted(rew, key=lambda k: rew[k])
    vals = [100 * rew[k] for k in names]
    fig, ax = plt.subplots(figsize=(3.4, 3.1))
    colors = ["#B0BEC5" if v / 100 < graph else "#264653" for v in vals]
    ax.barh(range(len(names)), vals, color=colors, height=0.68)
    ax.set_yticks(range(len(names)))
    ax.set_yticklabels([n.replace(" (Reasoning=High)", "") for n in names], fontsize=6.6)
    for x, lo, hi, lab, c, ls in [(graph, *t["graph_correct"]["ci95_incident_cluster"], "graph baseline", "#E76F51", "-"),
                                  (table, *t["table_correct"]["ci95_incident_cluster"], "alert-table baseline", "#2A9D8F", "--")]:
        ax.axvspan(100 * lo, 100 * hi, color=c, alpha=0.12, lw=0)
        ax.axvline(100 * x, color=c, ls=ls, lw=1.2, label=f"{lab} ({100 * x:.1f})")
    ax.set_xlabel("ExCyTIn test score (%): models = reported mean reward;\nbaselines = exact match, no LLM, no log query",
                  fontsize=6.8)
    ax.set_xlim(0, 65)
    ax.legend(loc="lower right", fontsize=6.4, frameon=False)
    fig.tight_layout()
    fig.savefig(HERE / "figures" / "fig_shortcut.pdf")
    fig.savefig(HERE / "figures" / "fig_shortcut.png", dpi=200)
    print("ok", {k: m[k] for k in ("exNamed", "exGraph", "exTable", "exBelowGraph", "exBelowTable", "gHeldMajority")})


if __name__ == "__main__":
    main()
