"""Write tables/prompt_example.tex: the planner prompt of the running example, verbatim.

Source: the stopping study's archived journal for Llama-3.1-8B, run 0087 (sec-base-02, repeat 0,
hesp_eigc_blind_autostop), third planner request. The text is rendered by the same function
(hesp.llm.render_request) that produced the prompt the model received.
"""
import json
import sys
import tarfile
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "hesp_research"
sys.path.insert(0, str(ROOT))
from hesp.llm import SYSTEM, render_request  # noqa: E402

ARCHIVE = ROOT / "results" / "v09_llama8b" / "runs_archive.tar.gz"
RUN = "run0087_sec-base-02_0_hesp_eigc_blind_autostop/events.jsonl"
WIDTH = 56


def wrap(text):
    out = []
    for line in text.splitlines():
        out += textwrap.wrap(line, WIDTH, subsequent_indent="    ", break_on_hyphens=False) or [""]
    return out


def main():
    with tarfile.open(ARCHIVE) as tar:
        events = [json.loads(l) for l in tar.extractfile(RUN).read().decode("utf-8").splitlines()]
    requests = [e["request"] for e in events if e["kind"] == "planner_request"]
    lines = ["% generated by paper/make_prompt_appendix.py -- do not edit",
             r"\begin{Verbatim}[fontsize=\scriptsize,frame=single,framesep=3pt,label={system message}]"]
    lines += wrap(SYSTEM)
    lines += [r"\end{Verbatim}", r"\vspace{6pt}",
              r"\begin{Verbatim}[fontsize=\scriptsize,frame=single,framesep=3pt,label={user message, third request}]"]
    lines += wrap(render_request(requests[2]))
    lines += [r"\end{Verbatim}"]
    out = Path(__file__).resolve().parent / "tables" / "prompt_example.tex"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {out} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
